herocollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('heros/', views.heros_index, name='index'),
    path('heros/<int:hero_id>/', views.heros_detail, name='detail'),
    path('heros/create/', views.HeroCreate.as_view(), name='heros_create'),
    path('heros/<int:pk>/update/', views.HeroUpdate.as_view(), name='heros_update'),
    path('heros/<int:pk>/delete/', views.HeroDelete.as_view(), name='heros_delete'),
    path('heros/<int:hero_id>/add_fighting/', views.add_fighting, name='add_fighting'),
      path('heros/<int:hero_id>/assoc_power/<int:power_id>/', views.assoc_power, name='assoc_power'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
VILLAINS = (
    ('Cheetah', 'Cheetah'),
    ('Lex Luther', 'Lex Luther'),
    ('Green Gobblin', 'Green Gobblin'),
    ('Joker', 'Joker'),
    ('Mystic', 'Mystic')
)

class Power(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return (self.name)

    def get_absolute_url(self):
        return reverse ('powers_detail', kwargs={'pk': self.id})

class Hero(models.Model):
    heroname = models.CharField(max_length=100)
    realname = models.CharField(max_length=100)
    superpower = models.CharField(max_length=100)
    weapon = models.CharField(max_length=100)
    weakness = models.CharField(max_length=100)
    powers = models.ManyToManyField(Power)

    def __str__(self):
        return self.heroname
   
    def get_absolute_url(self):
        return reverse('detail', kwargs={'hero_id': self.id})

class Fighting(models.Model):
    date = models.DateField()
    villain = models.CharField(max_length=50,
    choices=VILLAINS,
    default=VILLAINS [0][0]
    )

    hero = models.ForeignKey(Hero, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_villain_display()} on {self.date}"

    class Meta:
        ordering = ['date']

main_app/forms.py
from django.forms import ModelForm
from .models import Fighting

class FightingForm(ModelForm):
  class Meta:
    model = Fighting
    fields = ['date', 'villain']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Hero, Power
from .forms import FightingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def heros_index(request):
    heros = Hero.objects.all()
    return render(request, 'heros/index.html', {'heros': heros})

def heros_detail(request, hero_id):
  hero = Hero.objects.get(id=hero_id)
  powers_hero_doesnt_have = Power.objects.exclude(id__in = hero.powers.all().values_list('id'))
  fighting_form = FightingForm()
  return render(request, 'heros/detail.html', { 
    'hero': hero, 
    'fighting_form': fighting_form,
    'powers': powers_hero_doesnt_have
   })

def add_fighting(request, hero_id):
  form = FightingForm(request.POST)
  if form.is_valid():
    new_fighting = form.save(commit=False)
    new_fighting.hero_id = hero_id
    new_fighting.save()
  return redirect('detail', hero_id=hero_id)

class HeroCreate(CreateView):
  model = Hero
  fields = '__all__'
 
class HeroUpdate(UpdateView):
  model = Hero
  fields = ['superpower', 'weapon', 'weakness']

class HeroDelete(DeleteView):
  model = Hero
  success_url = '/heros/'

class PowerList(ListView):
  model = Power

class PowerDetail(DetailView):
  model = Power

class PowerCreate(CreateView):
  model = Power
  fields = '__all__'

class PowerDelete(DeleteView):
  model = Power
  success_url = '/powers/'

def assoc_power(request, hero_id, power_id):
  Hero.objects.get(id=hero_id).powers.add(power_id)
  return redirect('detail', hero_id=hero_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Hero Collector</h1>
<hr />
<p>Hire the Hero Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hero Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;HeroCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'heros_create' %}">Add A Hero</a></li>
          <li><a href="{% url 'index' %}">View All My Heros</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Hero Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/heros/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Hero Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ hero.heroname }}</span>
        <p>Real Name: {{ hero.realname }}</p>
        <p>Superpower: {{ hero.superpower }}</p>
        <p>Weapon: {{ hero.weapon }}</p>
        <p>Weakness: {{ hero.weakness }}</p>
        
      </div>
      <div class="card-action">
        <a href="{% url 'heros_update' hero.id %}">Edit</a>
        <a href="{% url 'heros_delete' hero.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_fighting' hero.id %}" method="post">
        {% csrf_token %}
        {{ fighting_form.as_p }}
        <input type="submit" class="btn" value="Add Fight">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Villain</th></tr>
      </thead>
      <tbody>
        {% for fighting in hero.fighting_set.all %}
          <tr>
            <td>{{fighting.date}}</td>
            <td>{{fighting.get_villain_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ hero.heroname }}'s Powers</h3>
    {% if hero.powers.count %}
      {% for power in hero.powers.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <p>The power of <span>{{ power.name }}</span></p>
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Other Powers</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Powers</h3>
    {% if powers.count %}
      {% for power in powers.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <p>The power of <span>{{ power.name }}</span></p>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_power' hero.id power.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{hero.heroname}} Already Has All Powers Available</h5>
    {% endif %}
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  var selectEl = document.getElementById('id_villain');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/heros/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Hero List</h1>

{% for hero in heros %}
  <div class="card">
    <a href="{% url 'detail' hero.id %}">
    <div class="card-content">
      <span class="card-title">{{ hero.heroname }}</span>
      <p>Real Name: {{ hero.realname }}</p>
      <p>Superpower: {{ hero.superpower }}</p>
      <p>Weapon: {{ hero.weapon }}</p>
      <p>Weakness: {{ hero.weakness }}</p>
    </div>
    </a>
  </div>

{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>HOME</h1>

{% endblock %}

main_app/templates/main_app/hero_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Hero</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.heroname }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' hero.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/hero_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.heroname}}</span></h1>
  {% else %}
    <h1>Add Hero</h1>
  {% endif %}
  <h2>AKA: <span class="teal-text">{{object.realname}}</span></h2>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}